server:
  port: 8763
eureka:
  instance:
    hostname: client
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defultZone: http://localhost:8761/eureka
spring:
  application:
    name: erueka-provider
