server:
  port: 8761
eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false #表明该服务不需要向eureka 注册自己的信息
    fetch-registry: false #表名该服务不会向eureka获取注册信息
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
spring:
  application:
    name: erueka-server
